### ISSUE TITLE
Change Roundware Database system?

### ISSUE THREAD

**Issue by eosrei** [roundware/roundware-server#184]
Roundware Server is currently using MySQL, but there has been discussion about changing database systems. If we are going to make a drastic change, such as the database system, is ideal to do it now since we *probably* know of all existing installations. It'll be much easier to make the change now since it won't need to be so thoroughly documented and tested.

Other database options:
* MariaDB
* PostGreSQL
* Mongo? Couch? SQLite?!

It seems to me that PostgreSQL is probably the best option since it will/should make it far easier to support #98 plus all other GIS related features. A database converter: https://github.com/lanyrd/mysql-postgresql-converter Lots of discussion: http://www.wikivs.com/wiki/MySQL_vs_PostgreSQL

**Comment by eosrei** [comment]
Some possibilities to deal with the database conversion:
* http://pgloader.io/howto/mysql.html
* https://github.com/philipsoutham/py-mysql2pgsql

Expected upgrade procedure, ideally this will be a pgsql-upgrade.sh/py:
* Install PostresSQL
* Migrate data
* Deploy new code/config
* Uninstall MySQL

There will need to be thorough tests to confirm that Django migrations will accept the database change.

**Comment by eosrei** [comment]
@probabble I see you are working on this process. Have you looked into the data conversion options?

**Comment by probabble** [comment]
I haven't... how many deployments need to be migrated?

**Comment by hburgund** [comment]
Impossible to say the total deployments as I don't know who's grabbed the code and deployed something, but I can say that we are working directly on five different production servers currently, so that's the minimum.  Not a huge number, but enough that a manual intensive process would be a pain, and public enough (Smithsonian etc) that we want to avoid as much downtime as possible.

@probabble have you done db changes before with django?  I have not, but my impression is that fixtures in theory at least allow for exporting and importing in a db-type agnostic way?  But maybe this is just wishful thinking?

**Comment by probabble** [comment]
I've always used postgres with Django as my interest has always been around
the GIS stuff. Fixtures should continue to work if they are read in through
django's orm and not directly injected into the db. It seems that
there are quite
a number of ways
<https://wiki.postgresql.org/wiki/Converting_from_other_Databases_to_PostgreSQL>
to migrate existing databases to postgresql, but I don't have personal
experience with the chore.

**Comment by eosrei** [comment]
FWIW Roundware Server was originally created in pure Python. @hburgund and others added Django when a web interface was required. Long term (in-device audio for example) it may only be an Django application.

**Comment by hburgund** [comment]
Closed with #270 - migration to Postgres complete
