### ISSUE TITLE
api/2 design - Authentication/tokens

### ISSUE THREAD

**Issue by hburgund** [roundware/roundware-server#196]
I think that the biggest difference with api/2 is going to be introducing some form of authentication.  This has security benefits by allowing us to throttle requests on a per user basis as well as prepares us to allow _optional_ user accounts in the future (right?).

Here are a few basic questions that I think I understand from reading the [DRF auth page] (http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) and other references, but would be useful to get clarified here for all involved:
* how much of this functionality is provided by Django and DRF and we just have to implement vs having to build things?
* where do the tokens come from? what is their form? where are they stored?
* how are tokens included with each request? parameter of some sort?
* is it the tokens that can eventually be optionally tied to a user account?  will the user accounts be standard django accounts with particular restricted permissions based on an auth group?

**Comment by eosrei** [comment]
> how much of this functionality is provided by Django and DRF and we just have to implement vs having to build things?

That's still a bit TBD, but the majority of the function for authentication is already included. The primary Roundware specific issue is determining how we will support these "anonymous user accounts" so that email/password isn't required. I've worked out some details, but more thought needs to go into it so it can be seamless to the user. I'd *really* like to make it possible for users to "claim" their accounts, so they don't loose their upload and session history.

> where do the tokens come from?

POST api/2/obtain_token

> what is their form?

`Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b`

> where are they stored?

The mobile application stores the access token. It gets a token from the Roundware server when the app first started. It must store that token on the device and re-use it to access Roundware. If the token is lost, the user can either log in again (if they've created a full account) or the Server can create a new Django User Account and access token for anonymous accounts.

> how are tokens included with each request? parameter of some sort?

"For clients to authenticate, the token key should be included in the Authorization HTTP header. The key should be prefixed by the string literal "Token", with whitespace separating the two strings." Standard REST procedures.

> is it the tokens that can eventually be optionally tied to a user account? will the user accounts be standard django accounts with particular restricted permissions based on an auth group?

Yes.
