### ISSUE TITLE
No audio heard with request_stream 

### ISSUE THREAD

**Issue by multidynamic** [roundware/roundware-server#212]
Some observations, i have noticed I repeatedly get an audio stream with nothing heard.

repro with android client:
- go into Android settings, set Location to _Off_
- start our app (notice it has no location and makes a `request_stream` call without lat long)
- notice audio begins to play but nothing is heard

**Comment by eosrei** [comment]
@hburgund What should the stream contain in this case? Currently it's just dead air.

**Comment by multidynamic** [comment]
Also try this:
* go into Android settings, set Location to *On*
* return to app, wait a few moments
* relevant off-site audio heard

**Comment by eosrei** [comment]
The current APIv1 requires you to call `modify_stream` or `move_listener` with a valid in-project GPS coordinate. Perhaps it should fail without lat/long?

**Comment by multidynamic** [comment]
If fix for https://github.com/roundware/roundware-android/issues/42 prevents user access to Listen then this is moot for the end-user.

**Comment by eosrei** [comment]
We've got to keep these APIv1 calls the same to keep from breaking older RW Apps/Projects.

**Comment by hburgund** [comment]
@eosrei I'm not sure what the stream should contain in this scenario per the intention of the current code as I don't believe this situation was fully considered.  But I think the user should be notified of the issue when it affects the behavior of the app so they can remedy or at least know what's going on.  

In your above-described situation, does `request_stream` get sent without latitude of longitude parameters at all, or are they blank?  At one point, we substituted in 0/0 for some reason, I recall, but can't remember the reasoning (it was probably a hack for something).  It does seem weird that a silent stream would be created

The behavior should depend on whether the project is `geo-listen-enabled` or not.  Perhaps:

* if `geo-listen-enabled`=`true`
  * require `request_stream` to have lat/lon parameters
  * notify user of location issue if not available
  * perhaps play `out-of-range` audio stream?
* if `geo-listen-enabled`='false'
  * ignore lat/lon parameters if sent and don't require them
  * no user notifications necessary since playback is independent of location

Not sure I've fully considered the situation and don't have a device with me to test myself, but these are my initial thoughts...

**Comment by hburgund** [comment]
this is no longer an issue; seems like it was specific to the FAM project and may be helped by work on global listen and continuous mode as well as changes made to not require a `move_listener` call to start the speaker audio in the stream.
