### ISSUE TITLE
Document Stereo Panning functionality - What is it supposed to do.

### ISSUE THREAD

**Issue by eosrei** [roundware/roundware-server#219]
Please document your (@hburgund)  intended functionality for the stereo panning in the wiki. Maybe called "Audio asset/speak playback details" or something. Some questions:

* Is panning supposed to be random?
* Does it go back and forth constantly?
* Do audio tracks (playing assets) have their own pan control?
* Is panning delta always linear?
* How cool would it be to control this with the device compass with in-device audio?

*I can figure out the answers to some of these, but I'd like it out of your mind directly*

Created due to: #203

**Comment by sinabahram** [comment]
How cool would it be to control this with the device compass with in-device audio?

 

IMHO, very!? Not necessarily useful/helpful, but totally “cool!”

**Comment by hburgund** [comment]
Panning is first-gen Roundware functionality and is rudimentary, but still very useful for the aesthetic tuning of the system.  If memory serves, the panning functionality is supposed to behave as such:

* min and max pan positions are defined per audiotrack (-1.0 if full left and 1.0 is full right)
* min and max pan times are defined per audiotrack as well
* each audiotrack then proceeds to pick a random start and stop pan position within the defined range
* a pan time is also randomly chosen from the range
* then the asset (which is a mono audio file) is played back within the stream starting at the initial pan position and ending at the destination pan position taking the pan time to traverse the "distance" linearly
* when the pan destination is reached, the process starts over with a new pan destination and new pan time chosen (the previous pan destination becomes the pan origin of the next step)

I'm not sure how this works in transitions from asset to asset; ie whether the process starts over or continues from where it left off.  Probably doesn't really matter, but I think it's the latter.

This is very useful not only for some audio variety and motion in the stereo field, but also for multiple audiotrack scenarios in which one track can be mainly left and the other mainly right etc.  When we gain the ability to filter audiotracks by tag (#189), this will be even more useful.

I think I touched on all of the above questions, but there might be more details you're looking for, so let me know.  

I am all for things like controlling panning with compass etc...totally cool.  I also think that adding "3D" sound so that sources could be localized directionally could be super cool and also potentially useful for low/no vision folks (maybe, @sinabahram?) for wayfinding.  We could have sounds emanate from the direction from which they originate allowing people to hear things that aren't where they are located, but are from the direction they are looking etc etc. 

The possibilities are HUGE!

**Comment by eosrei** [comment]
Please put details in the wiki and close this issue

**Comment by hburgund** [comment]
done...finally!

**Comment by 13rac1** [comment]
​Yay!​
