### ISSUE TITLE
Add languages field to Project model

### ISSUE THREAD

**Issue by IllyaMoskvin** [roundware/roundware-server#309]
For the new admin interface, we need a way to specify languages for each project. This will affect which localized strings you can add in other parts of the admin interface. We also need a way to toggle an "enabled" flag for languages on a project level. This allows editors to add a language to a project, but hide it from the public until all of the translations are ready.

Given that we already have a `Language` model, this shouldn't be terribly difficult server-side, but we will need to figure out a way to add an additional flag to the relationship (`enabled`). 

Sample expected APIv2 response, illustrating fields missing from `/api/2/projects/:id/`:

```
{
  "project_id": 1
  "name": "Test Project",
  [...]
  "languages": [
    {
      "id": 1,
      "enabled": true
    },
    {
      "id": 2,
      "enabled": false
    }
  ],
  [...]
}
```

**Comment by 13rac1** [comment]
Roundware has a custom translation system using `LocalizedString`. This may be the time to convert to the Django standard: https://docs.djangoproject.com/en/1.10/topics/i18n/translation/

**Comment by IllyaMoskvin** [comment]
That thought crossed my mind as well. I chatted with @hburgund a bit about it, maybe he could weigh in here? If we decide to adopt the Django standard, the sooner we do so, the easier it'll be to migrate. However, I don't have the time to do this conversion currently. The lack of ability to define `languages` on a `Project` level is a blocker for the admin interface. That's the only thing I *need* to continue work on the admin, which has to remain my highest priority, I'm afraid :worried:

**Comment by hburgund** [comment]
I am always a big proponent of using built-in features whenever possible, so I love the idea of using Django's translation features. But a while back, someone (I think maybe @grayb) investigated this and learned that this feature is really built for translating web pages rather than for providing different localized strings in response to certain api calls to be used by clients.

I do not remember the details and can't seem to find my notes now, but I do remember that it made sense at the time, though things may have changed in the interim or some misunderstanding may have happened. @grayb do you recall?

I did review the documentation briefly and it does seem to focus on web page translations with a base language string put into the template and then translations happen as needed, replacing that string. But I have only a rudimentary understanding, and the system may very well be much more flexible, so @eosrei if you have a clear idea of how the built-in system could fully replace what we have currently, please let us know as that would be great.

@IllyaMoskvin I of course understand that we can't do all this work right now, but if I can figure out what future direction makes the most sense, we can modify your current work to not waste effort and to future-proof as best as possible.

**Comment by grayb** [comment]
@hburgund, if I remember correctly, the trouble was that Django wants all the translation strings in what's called a message file - a plain text file containing an original match string, and the string to replace it with.  There would be one of these files for each language.  If you could write an interface to create and update these files it could be possible, but I got the impression from my research that they aren't meant to be used that way.

You could also just create your own translation tables inside the app, and lean on the Django admin for creating/editing.  The key to knowing which one to use is the HTTP Accept-Language header.  I'm not certain if the API framework supports it, but it probably does.

**Comment by 13rac1** [comment]
(What looks like) the standard for model translation: https://github.com/deschler/django-modeltranslation It's not built in, better than NIH

**Comment by hburgund** [comment]
thanks @grayb and @eosrei. It does seem that we need model translation, not just the built-in stuff and this app looks very helpful. It looks like it could be a bit awkward, though, since a single RW server can handle multiple projects yet each project will have different active languages. As I understand it, this will result in lots of empty/unused fields, but maybe that's fine.

I will continue to research this issue to figure out the best ultimate solution, but since we don't have the resources to implement a full re-haul now, I will go ahead and make the minor server changes to support the current admin development so things don't get stuck there. It seems to me that no matter what ultimate solution for translation we end up using, we will still want the ability to specify on a project level which languages are available/active, so I don't see this work as superfluous.

**Comment by IllyaMoskvin** [comment]
Thank you to everyone who has pitched in with their thoughts on localization so far. My initial impression from the docs was similar to @grayb's – I thought that Django's built-in translation was more of a file-based, hard-coded system mostly meant for swapping out microcopy.

I also don't feel all that great about `django-modeltranslation`. That is a *lot* of open issues, and little activity for four months. Better than NIH, though, can't argue with that!

Please see #311 for a related issue. There's some relevant thoughts on `django-modeltranslation` there as well.
